name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/lvp_icd.x86_64.json
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          cache: true
      - name: Install llvmpipe Vulkan driver
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-vulkan-drivers
      - name: Run tests
        run: |
          set -euo pipefail
          cargo test --all --locked | tee test-results.txt
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt
