name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true

permissions:
  contents: write  # allow release creation
  
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    env:
      VK_ICD_FILENAMES: /usr/share/vulkan/icd.d/lvp_icd.x86_64.json
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install llvmpipe Vulkan driver
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y mesa-vulkan-drivers
          sudo apt-get install -y libasound2-dev

      - name: Build
        run: cargo build --release

      - name: Prepare artifact
        shell: bash
        run: |
          mkdir -p artifacts
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            cp target/release/meshi.dll artifacts/
            cp target/release/meshi.dll.lib artifacts/
            (cd artifacts && powershell -Command "Compress-Archive -Path meshi.dll,meshi.dll.lib -DestinationPath meshi-windows.zip")
            rm artifacts/meshi.dll artifacts/meshi.dll.lib
            echo 1
            ls artifacts/
          else
            cp target/release/libmeshi.so artifacts/meshi.so
            echo 2
            ls .
            ls artifacts/
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: meshi-${{ matrix.os }}
          path: artifacts/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: meshi-*
          merge-multiple: true

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create header archives
        shell: bash
        run: |
          mkdir -p artifacts
          tar -czf artifacts/meshi-c-headers.tar.gz -C include meshi
          (cd include && zip -r ../artifacts/meshi-c-headers.zip meshi)
          echo 3
          ls artifacts/
          ls .

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.tag }}
          name: "${{ github.event.inputs.tag }}"
          files: |
            artifacts/meshi*
            artifacts/meshi-ubuntu-latest.zip
            artifacts/meshi-windows-latest.zip
            artifacts/meshi-c-headers.tar.gz
            artifacts/meshi-c-headers.zip
